### ISSUE TITLE
Topics for Hackathon 2019

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#373] opened 2019-07-25 12:54 UTC
### The Story So Far
We are planning a hackathon November 6-8 in Bethesda, Maryland. We will use this issue to discuss what possible items could be added to its agenda. This will be kept up to date below. Items with ✅ are approved by consensus and struck-out items were proposed but agreed not to be done. 

### Proposed Items
- Lecture/group discussion on math steps
- Decision Tree alternative
- New dimensionality estimation in PCA
- Increased compatibility for a combination tedana-MELODIC approach

**Comment by tsalo** [comment] 2019-07-25 14:39
I think I'd frame the decision tree rewrite as more of development of an alternative decision tree, since the existing one is published and citable.

I'd also like to proposed the addition of a new dimensionality estimation method within TEDPCA, as well as some support (either in documentation or in code) for the MELODIC + tedana approach.

**Comment by handwerkerd** [comment] 2019-07-26 20:30
Thanks @jbteves for starting this issue/discussion!

I'm hoping we resolved the dimensionality reduction PCA step before the hackathon! Similarly, I don't see a good reason to focus on specifically merging MELODIC & tedana, but if the code is sufficiently modularized to take pre-calculated components then it shouldn't be hard to combine with MELODIC.

For Decision Tree alternative, I see 3 related parts that could benefit from in-person collaboration:
1. Decide what/how to modularize
2. Create the kundu decision tree within the new modularized code base.
3. Discuss and create a trimmed and simplified decision tree inspired by the kundu decision tree
4. Discuss if we want a bigger rethinking of the decision tree

Addition topic:
Denoising quality metrics: We need better and more automated metrics for denoising quality so that, if we do things like comparing decision tree approaches, we can consistently evaluate and compare them. I'm not sure this will be a coding focus, but some in-person discussion would be useful.

**Comment by CesarCaballeroGaudes** [comment] 2019-07-30 15:09
Hello,
I was actually thinking that an empirical (and maybe useful) way to assess the true dimensionality of the IC components is through ICASSO so that extra components that are probably describing random noise don't repeat across several iterations of ICA. Therefore, if you think it is a good idea I could work towards an implementation of ICASSO during the hackaton. I'm also happy to discuss other issues related to the decision tree.

**Comment by handwerkerd** [comment] 2019-08-05 15:50
Discussing or working on the code to better compare how changes to the pipeline will affect results. (based on a comment I made in #274 )

**Comment by KirstieJane** [comment] 2019-08-14 08:29
Copying across from July dev meeting minutes:

> Issue #352
> There isn’t a definitive answer right now.
> **Semi-long term action item**: Max echo time is a fairly common question. The documentation should include some information on how to think about this topic. It might be possible to add a quick sentence or two, but a more definitive answer for this would be good to figure out in the long term.
> The second issue was the math on Rho & Kappa to help people better understand.
> Clarifying what makes sense might be a good topic for the hackathon: The hackathon might be a good place to decide what fundamental things should or shouldn’t be changed in the pipeline. > ACTION: Create an issue to discuss what *could* be discussed at the hackathon….and add this point to it! ✅

**Comment by tsalo** [comment] 2019-10-10 20:10
I'd like to talk about how multi-echo denoising can be combined with complex-valued denoising methods, if possible. I haven't seen much work in the intersection of these two domains.

**Comment by CesarCaballeroGaudes** [comment] 2019-10-10 21:04
That's a very interesting topic that I have been thinking about lately, and also about denoising. An important point is that, according to the anatomical QSM literature, saving both phase and magnitude images from all the coils seems to be critical to achieve a good reconstruction of the phase information. This might be an important burden in terms of memory because in fMRI we collect one image every TR seconds. So, it would mean that we need 2 x Number of Coils x Number of echoes per TR.

**Comment by tsalo** [comment] 2019-10-11 13:18
Does that mean that phase-based denoising methods are invalid with standard complex reconstruction, or just that they won't perform as well as they could? A research scientist in my lab was also interested in using coil-specific data, or even working on k-space more, but we realized that it would be pretty difficult to implement. My hope is that, since standard complex reconstruction is pretty easy to do (at least with the CMRR sequence) and complex data is supported in most BIDS tools now, multi-echo folks would be more willing/able to acquire complex data now. At least, as long as it's useful.

I was thinking that we could try to figure out how established phase-based denoising methods, like phase regression and complex modeling, would interact with multi-echo denoising. Not to mention effective k-space-based methods.

**Comment by CesarCaballeroGaudes** [comment] 2019-10-11 13:22
I would say that they won't perform as well as they could. Yes, we have also collected phase image with the CMRR sequence, though not ME yet though. In any case, this is a very interesting topic for discussion during the hackathon!!

**Comment by emdupre** [comment] 2019-10-11 18:48
I'm a little worried that this is veering away from something that we could reasonably progress on during the hackathon itself. It's great to have people face to face to have these kinds of conversations over coffee, lunch, etc. But I just don't want to set expectations that this is something we should prioritize during development time ! I think we have a few pots to tend to before tackling this kind of extension.

**Comment by CesarCaballeroGaudes** [comment] 2019-10-12 09:05
I completely agree. We must focus on advancing current pipeline and active developments, and have these interesting discussions over coffee, lunch, dinner. The particular case of using the phase in ME-fMRI procedures would require substantial thoughts and scientific research, even enough for a PhD thesis!!!

**Comment by tsalo** [comment] 2019-11-18 00:22
Should we close this now that the hackathon is over?

**Comment by emdupre** [comment] 2019-11-18 00:46
Sure ! Let's open a new one to write up a summary :smile_cat:

**Closed** 2019-11-18 00:51 UTC
Labels: hackathon, high-priority
