### ISSUE TITLE
TypeError problem from monoexponential.py

### ISSUE THREAD

**Issue by d3christ** [ME-ICA/tedana#141] opened 2018-10-16 23:30 UTC
We are running tedana and are getting the following TypeError. Any ideas on what could be the cause?

```
$ tedana -d BOLD_SmokeCues_MultiTE_12.nii BOLD_SmokeCues_MultiTE_12a.nii BOLD_SmokeCues_MultiTE_12b.nii -e 13 36 58
/u/home/d/dpchrist/.local/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
/u/home/d/dpchrist/.local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/u/home/d/dpchrist/.local/bin/tedana", line 11, in <module>
    load_entry_point('tedana==0.0.4', 'console_scripts', 'tedana')()
  File "/u/home/d/dpchrist/.local/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 447, in _main
    tedana_workflow(**vars(options))
  File "/u/home/d/dpchrist/.local/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 371, in tedana_workflow
    t2s, s0, t2ss, s0s, t2sG, s0G = model.fit_decay(catd, tes, mask, masksum)
  File "/u/home/d/dpchrist/.local/lib/python3.6/site-packages/tedana/model/monoexponential.py", line 90, in fit_decay
    betas = np.linalg.lstsq(X, log_data, rcond=None)[0]
  File "/u/local/apps/python/3.6.1/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/linalg/linalg.py", line 1961, in lstsq
    0, work, -1, iwork, 0)
TypeError: must be real number, not NoneType
```

**Comment by tsalo** [comment] 2018-10-17 00:18
It looks like the problem is the argument `rcond` in version 1.12.1 of numpy. To replicate with that version:
```python
import numpy as np
a = np.random.random((100, 1))
b = np.random.random((100, 10))
betas = np.linalg.lstsq(a, b, rcond=None)[0]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1961, in lstsq
    0, work, -1, iwork, 0)
```

I think the best solution would be to update numpy. I believe that `tedana` requires 1.14 at minimum.

**Comment by emdupre** [comment] 2018-10-17 01:15
Just to :+1: @tsalo's suggestion, it looks like your `numpy` version is likely causing the error. If you could update that library @d3christ, hopefully that will resolve the issue ! Let us know how it goes.

**Comment by tsalo** [comment] 2018-10-24 12:40
Sorry for the delay! Did it finish running at any point? In my experience, tedana takes about 20-30 minutes to finish running on a single run.

**Comment by jbteves** [comment] 2019-04-20 14:15
@tsalo if we don't hear back by May 1 I'd like to propose we close this issue. I failed to mention more details in #188 but the symptoms described above were very similar to the all-cores problem I had on my server, so I would suspect that the user above had the same problem. If somebody comes along later with the same problem we can re-open this one.

**Comment by tsalo** [comment] 2019-04-20 17:39
I think it's reasonable to close it now. The last update was a couple of months ago.

**Closed by tsalo** 2019-04-20 17:39 UTC
Labels: question
